// Design: Azul Executivo adaptado ao Leo — foto em primeiro plano, moldura técnica e CTA de WhatsApp como ação central.
import { ArrowUpRight, MapPin, MessageCircle, Phone } from "lucide-react";

const WHATSAPP_URL = "https://wa.me/5531971092507?text=Ol%C3%A1%20Leo%20Veio%2C%20gostaria%20de%20olhar%20um%20carro%20com%20o%20papito%21";
const PHONE_URL = "tel:+5531971092507";

export default function LeoCarcaca() {
  return <main className="leo-page"><div className="leo-noise" aria-hidden="true" /><header className="leo-header"><div className="brand-lockup"><span className="brand-mark">B</span><span><small>BRASAUTO</small><b>IPATINGA</b></span></div><span className="leo-status"><i /> Atendimento direto</span></header><section className="leo-main container"><div className="leo-photo-wrap"><div className="leo-photo-frame"><img src="/manus-storage/leo-carcaca_a5f81f4c.png" alt="Leonardo Meireles, conhecido como Leo Carcaça" /></div><span className="leo-photo-label">LEO · 01</span></div><div className="leo-copy"><p className="kicker blue">CONSULTOR ESPECIALISTA · BRASAUTO</p><h1>Leo<br /><em>Carcaça.</em></h1><p className="leo-real-name">Leonardo Meireles</p><p className="leo-lede">Seu próximo carro pode começar com uma conversa boa, direta e do jeito certo.</p><div className="leo-brands"><span>Marcas atendidas</span><div><b>PEUGEOT</b><i>·</i><b>CITROËN</b><i>·</i><b>BRASAUTO</b></div></div><a className="leo-primary" href={WHATSAPP_URL} target="_blank" rel="noreferrer"><MessageCircle size={21} /> Falar com o Leo <ArrowUpRight size={19} /></a><div className="leo-actions"><a href={PHONE_URL}><Phone size={18} /><span><small>Telefone</small>31 97109-2507</span></a><a href="https://www.google.com/maps/search/?api=1&query=Brasauto+Ipatinga" target="_blank" rel="noreferrer"><MapPin size={18} /><span><small>Brasauto Ipatinga</small>Ver localização</span></a></div><p className="leo-whatsapp-note">Ao tocar no botão, o WhatsApp abre com a mensagem:<br /><strong>“Olá Leo Veio, gostaria de olhar um carro com o papito!”</strong></p></div></section><footer className="leo-footer"><span>Peugeot · Citroën · Brasauto Ipatinga</span><span>Atendimento com personalidade.</span></footer></main>;
}
